// tailwind.config.js
/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./resources/**/*.blade.php",
    "./resources/**/*.js",
    "./resources/**/*.vue", // Quan trọng: Đảm bảo có Vue files
  ],
  theme: {
    extend: {
      colors: {
        primary: '#b3111b',
        secondary: '#a03e38',
        'primary-light': '#F0807C',
        'on-primary-container': '#fff6f5',
        'surface-variant': '#f1f5f9',
        'on-secondary': '#ffffff',
        'on-error-container': '#93000a',
        background: '#f7f9fb',
        'on-tertiary-fixed': '#001f2a',
        'tertiary-fixed': '#bce9ff',
        'on-primary-fixed-variant': '#930010',
        'surface-container-highest': '#e2e8f0',
        'surface-container-high': '#f1f5f9',
        'error-container': '#ffdad6',
        'surface-container-lowest': '#ffffff',
        'primary-fixed-dim': '#ffb3ac',
        'on-error': '#ffffff',
        'surface-container': '#f8fafc',
        'tertiary-fixed-dim': '#79d2f7',
        'surface-dim': '#f1f5f9',
        'surface-tint': '#ba181f',
        'on-tertiary': '#ffffff',
        'on-surface-variant': '#5b403d',
        'surface-container-low': '#ffffff',
        'primary-fixed': '#ffdad6',
        'inverse-surface': '#3e2c2a',
        'surface-bright': '#ffffff',
        'on-tertiary-container': '#f2faff',
        'on-tertiary-fixed-variant': '#004d64',
        outline: '#906f6c',
        'on-secondary-fixed': '#410003',
        'on-background': '#271716',
        error: '#ba1a1a',
        'tertiary-container': '#007c9e',
        'on-secondary-container': '#741e1b',
        'on-primary-fixed': '#410003',
        'primary-container': '#d73030',
        tertiary: '#00627d',
        'inverse-on-surface': '#ffedeb',
        'secondary-fixed': '#ffdad6',
        'on-secondary-fixed-variant': '#812723',
        'on-surface': '#271716',
        'secondary-fixed-dim': '#ffb3ac',
        'inverse-primary': '#ffb3ac',
        'secondary-container': '#fe857c',
        surface: '#ffffff',
        'on-primary': '#ffffff',
        'outline-variant': '#e2e8f0',
      },
      backgroundImage: {
        'gradient-red': 'linear-gradient(180deg, #D72D36 0%, #520011 100%)',
      },
      fontFamily: {
        headline: ['Manrope'],
        body: ['Inter'],
        label: ['Inter'],
        display: ['Manrope'],
        manrope: ['Manrope'],
      },
    },
  },
  plugins: [],
}